version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - api

  classifier:
    build: ./classifier
    volumes:
      - ./classifier:/usr/src/app
    ports:
      - 8084:8084

  api:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8082:8082
    depends_on:
      - classifier
